# Generated by Django 3.2.9 on 2022-03-18 21:05

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shift_maker", "0005_auto_20220317_1545"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcontent",
            name="detail",
            field=models.TextField(blank=True, verbose_name="テキスト"),
        ),
        migrations.AlterField(
            model_name="shift",
            name="deadline",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 3, 21, 21, 5, 58, 881669, tzinfo=timezone.utc
                )
            ),
        ),
    ]
