# Generated by Django 3.2.3 on 2022-03-28 01:42

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("shift_maker", "0008_alter_shift_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="deadline",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 3, 31, 1, 42, 52, 628826, tzinfo=timezone.utc
                )
            ),
        ),
    ]
